version: '3.8'

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
    volumes:
      - ./.next:/app/.next
    restart: unless-stopped
    networks:
      - web
    labels:
      traefik.enable: true
      traefik.http.routers.web.rule: Host("web.bot.techaas.tech")
      traefik.http.routers.web.tls: true
      traefik.http.routers.web.entrypoints: websecure
      traefik.http.routers.web.tls.certresolver: prod
